version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      development-dependencies:
        dependency-type: development
        exclude-patterns:
          - effect
        update-types:
          - minor
          - patch
      production-dependencies:
        dependency-type: production
        exclude-patterns:
          - effect
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"
